# https://taskfile.dev

version: "3"

tasks:
  default:
    cmds:
      - dotnet format whitespace
      - dotnet format style --severity info
      - dotnet build
      - dotnet test
    silent: true
