@HostAddress = http://localhost:57679
@ApiVersion = 1
@AccessToken = xyz

###
GET {{HostAddress}}/api/{{ApiVersion}}/License/System

###
GET {{HostAddress}}/api/{{ApiVersion}}/Company
Authorization: Bearer {{AccessToken}}

###
POST {{HostAddress}}/api/{{ApiVersion}}/Company
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Brooks Group"
}

###
PUT {{HostAddress}}/api/{{ApiVersion}}/Company/40442946197127168
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "name": "Brooks Group"
}

###
GET {{HostAddress}}/api/{{ApiVersion}}/Employee
Authorization: Bearer {{AccessToken}}

###
POST {{HostAddress}}/api/{{ApiVersion}}/Employees
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "firstName": "Main",
  "lastName": "Character",
  "fullName": "Main character"
}

###
PUT {{HostAddress}}/api/{{ApiVersion}}/Employees/40450939236122624
Authorization: Bearer {{AccessToken}}
Content-Type: application/json

{
  "firstName": "Main",
  "lastName": "Character",
  "fullName": "Main character"
}

###
GET {{HostAddress}}/api/{{ApiVersion}}/Employees?PageNumber=1&PageSize=10
Authorization: Bearer {{AccessToken}}
